language: r
r: release
cache: packages
before_install:
  - openssl aes-256-cbc -K $encrypted_71b396cbdae4_key -iv $encrypted_71b396cbdae4_iv
    -in inst/extdata/sql.yaml.enc -out $HOME/sql.yaml -d
warnings_are_errors: false


matrix:
  include:
    - os: linux
      sudo: false
    - os: osx
      osx_image: xcode7.3
      latex: false
